M48
; DRILL file {KiCad 7.0.9} date Friday, April 05, 2024 at 10:47:15 AM
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2024-04-05T10:47:15+01:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,7.0.9
; #@! TF.FileFunction,NonPlated,1,4,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.650
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C1.600
%
G90
G05
T1
X80.0Y-258.86
X80.0Y-264.64
T2
X76.7Y-248.25
T0
M30
